### ISSUE TITLE
SQL code used by some containers can cause PG deadlocks, and the containers crash in response

### ISSUE THREAD

**Issue by simon-20** [IATI/refresher#357]
**Brief Description**
This issue occurs regularly but not frequently, and has been doing so as far as our logs go back. The issue is that some of the SQL `UPDATE` commands which reset the `*_start` flags for each pipeline stage can enter deadlock. Here's an example from the Postgres logs:

```
2024-11-20 00:20:47 UTC-673d2b5e.880d0-ERROR:  deadlock detected
2024-11-20 00:20:47 UTC-673d2b5e.880d0-DETAIL:  Process 557264 waits for ShareLock on transaction 868302883; blocked by process 557268.
	Process 557268 waits for ShareLock on transaction 868302881; blocked by process 557264.
	Process 557264: 
	        UPDATE document
	        SET clean_start = null
	        WHERE clean_end is null
	    
	Process 557268: 
	        UPDATE document
	        SET flatten_start=null
	        WHERE flatten_end is null

```

This can happen (even though the data being updated is not the same) because Postgres locks the entire row when updating, the two updates may contain the same rows, and the order in which `UPDATE` processes the rows is not deterministic.

**Severity**
High

**Issue Location**
[one of the database statements above](https://github.com/IATI/refresher/blob/e0bc872d29591339815d95363b40889f19d4e4e5/src/library/db.py#L427)

**Expected Results/Behaviour**
Minimum: the containers should not crash when deadlocks occur.
Ideal: use `SELECT FOR UPDATE` to ensure the `UPDATE`s process records in the same order; this should then cause one to wait for another, and avoid deadlock.

**Comment by simon-20** [comment]
This happened against today in the `clean` stage:

```log
2025-10-15 04:50:15,212 - clean - INFO - Copying 0 valid IATI files in a single process.	
2025-10-15 04:50:15,971 - solrize - INFO - Removing all docs for doc with hash: baf081acb8ef964306f891da76bf9e975f005b8e and id: 50df1c6f-4310-4ef4-a0ac-408a1348b06e	
2025-10-15 04:50:16,052 - solrize - INFO - Adding docs for hash: baf081acb8ef964306f891da76bf9e975f005b8e and id: 50df1c6f-4310-4ef4-a0ac-408a1348b06e	
2025-10-15 04:50:16,669 - clean - INFO - Starting clean of invalid activities documents to save to clean container...	
2025-10-15 04:50:16,669 - clean - INFO - copy_valid Finished.	
2025-10-15 04:50:16,707 - clean - INFO - Resetting those unfinished	
2025-10-15 04:50:21,864 - solrize - INFO - Batch length of 1558 transaction greater than 500 for hash: baf081acb8ef964306f891da76bf9e975f005b8e id: 50df1c6f-4310-4ef4-a0ac-408a1348b06e	
2025-10-15 04:50:27,950 - flatten - INFO - Flattening and storing 0 IATI files in a single process.	
2025-10-15 04:50:28,044 - flatten - INFO - Finished.	
2025-10-15 04:50:29,203 - handler - ERROR - cleanloop stage failed (full traceback follows)	
CONTEXT:  while rechecking updated tuple (150,21) in relation "document"	
Process 255782 waits for ShareLock on transaction 220984684; blocked by process 255819.	
    db.resetUnfinishedCleans(conn)	
    curs.execute(sql)	
DETAIL:  Process 255819 waits for ShareLock on transaction 220984639; blocked by process 255782.	
psycopg2.errors.DeadlockDetected: deadlock detected	
    clean_invalid()	
2025-10-15 04:50:31,003 - handler - ERROR - Traceback (most recent call last):	
HINT:  See server log for query details.	
  File "/code/library/clean.py", line 260, in service_loop	
  File "/code/library/clean.py", line 221, in clean_invalid	
	
	
  File "/code/handler.py", line 60, in main	
  File "/code/library/db.py", line 443, in resetUnfinishedCleans	
    clean.service_loop()	
Sentry is attempting to send 3 pending events	
Waiting up to 2 seconds	
Press Ctrl-C to quit	

```

**Comment by simon-20** [comment]
And again yesterday:

```
2025-12-08 13:00:21,734 - validate - INFO - Finished validation.	
10.92.0.5 - prom [08/Dec/2025:13:00:39 +0000] "GET /c3_clean HTTP/1.1" 200 656 "-" "Prometheus/2.54.1"	
10.92.0.5 - prom [08/Dec/2025:13:00:40 +0000] "GET /c1_refresh HTTP/1.1" 200 724 "-" "Prometheus/2.54.1"	
2025-12-08 13:00:42,047 - handler - ERROR - cleanloop stage failed (full traceback follows)	
  File "/code/handler.py", line 60, in main	
2025-12-08 13:00:42,331 - handler - ERROR - Traceback (most recent call last):	
DETAIL:  Process 1951421 waits for ShareLock on transaction 247836518; blocked by process 1951498.	
psycopg2.errors.DeadlockDetected: deadlock detected	
    db.resetUnfinishedCleans(conn)	
    curs.execute(sql)	
HINT:  See server log for query details.	
	
  File "/code/library/clean.py", line 82, in copy_valid	
  File "/code/library/db.py", line 443, in resetUnfinishedCleans	
Process 1951498 waits for ShareLock on transaction 247836443; blocked by process 1951421.	
  File "/code/library/clean.py", line 259, in service_loop	
    clean.service_loop()	
CONTEXT:  while rechecking updated tuple (2843,1) in relation "document"	
    copy_valid()	
	
Sentry is attempting to send 3 pending events	
Press Ctrl-C to quit	
Waiting up to 2 seconds	
10.92.0.6 - prom [08/Dec/2025:13:00:48 +0000] "GET /c6_solrize HTTP/1.1" 200 615 "-" "Prometheus/2.54.1"	
2025-12-08 13:00:52,630 - handler - INFO - Starting prometheus metrics exporter...
```

And:

```
2025-12-08 13:00:59,030 - flatten - INFO - Flattening and storing 0 IATI files in a single process.	
2025-12-08 13:00:59,132 - flatten - INFO - Finished.	
10.92.0.6 - prom [08/Dec/2025:13:01:01 +0000] "GET /c4_flatten HTTP/1.1" 200 614 "-" "Prometheus/2.54.1"	
2025-12-08 13:01:09,407 - handler - ERROR - lakifyloop stage failed (full traceback follows)	
  File "/code/library/lakify.py", line 186, in main	
    cur.execute(sql)	
  File "/code/library/lakify.py", line 175, in service_loop	
DETAIL:  Process 1951541 waits for ShareLock on transaction 247836587; blocked by process 1951539.	
HINT:  See server log for query details.	
    db.resetUnfinishedLakifies(conn)	
CONTEXT:  while rechecking updated tuple (1322,24) in relation "document"	
psycopg2.errors.DeadlockDetected: deadlock detected	
2025-12-08 13:01:09,927 - handler - ERROR - Traceback (most recent call last):	
	
	
  File "/code/library/db.py", line 398, in resetUnfinishedLakifies	
  File "/code/handler.py", line 56, in main	
    lakify.service_loop()	
    main()	
Process 1951539 waits for ShareLock on transaction 247836588; blocked by process 1951541.	
Sentry is attempting to send 3 pending events	
Press Ctrl-C to quit	
Waiting up to 2 seconds	
2025-12-08 13:01:18,629 - handler - INFO - Starting prometheus metrics exporter...
```

And:

```
2025-12-08 13:01:38,259 - clean - INFO - Copying 0 valid IATI files in a single process.	
2025-12-08 13:01:39,254 - clean - INFO - copy_valid Finished.	
2025-12-08 13:01:39,254 - clean - INFO - Starting clean of invalid activities documents to save to clean container...	
2025-12-08 13:01:39,288 - clean - INFO - Resetting those unfinished	
10.92.0.5 - prom [08/Dec/2025:13:01:39 +0000] "GET /c3_clean HTTP/1.1" 200 657 "-" "Prometheus/2.54.1"	
10.92.0.5 - prom [08/Dec/2025:13:01:40 +0000] "GET /c1_refresh HTTP/1.1" 200 725 "-" "Prometheus/2.54.1"	
2025-12-08 13:01:40,351 - handler - ERROR - lakifyloop stage failed (full traceback follows)	
  File "/code/handler.py", line 56, in main	
2025-12-08 13:01:40,729 - handler - ERROR - Traceback (most recent call last):	
    lakify.service_loop()	
  File "/code/library/lakify.py", line 175, in service_loop	
  File "/code/library/lakify.py", line 186, in main	
    main()	
	
CONTEXT:  while rechecking updated tuple (1325,27) in relation "document"	
psycopg2.errors.DeadlockDetected: deadlock detected	
	
  File "/code/library/db.py", line 398, in resetUnfinishedLakifies	
DETAIL:  Process 1951565 waits for ShareLock on transaction 247836630; blocked by process 1951621.	
Process 1951621 waits for ShareLock on transaction 247836610; blocked by process 1951565.	
HINT:  See server log for query details.	
    cur.execute(sql)	
    db.resetUnfinishedLakifies(conn)	
Press Ctrl-C to quit	
Waiting up to 2 seconds	
Sentry is attempting to send 3 pending events	
2025-12-08 13:01:47,130 - handler - INFO - Starting prometheus metrics exporter...	
2025-12-08 13:01:47,239 - lakify - INFO - Start service loop	
2025-12-08 13:01:47,239 - lakify - INFO - Starting to Lakify...	
2025-12-08 13:01:47,338 - lakify - INFO - Resetting those unfinished	
10.92.0.6 - prom [08/Dec/2025:13:01:48 +0000] "GET /c6_solrize HTTP/1.1" 200 616 "-" "Prometheus/2.54.1"	
10.92.0.5 - prom [08/Dec/2025:13:01:54 +0000] "GET /c5_lakify HTTP/1.1" 200 616 "-" "Prometheus/2.54.1"	
10.92.0.5 - prom [08/Dec/2025:13:01:58 +0000] "GET /c2_validate HTTP/1.1" 200 674 "-" "Prometheus/2.54.1"	
2025-12-08 13:01:59,060 - clean - INFO - Cleaning and storing 0 IATI files in a single process.	
2025-12-08 13:01:59,097 - clean - INFO - clean_invalid Finished.	
2025-12-08 13:01:59,132 - flatten - INFO - Starting to flatten...	
2025-12-08 13:01:59,196 - flatten - INFO - Resetting those unfinished	
10.92.0.6 - prom [08/Dec/2025:13:02:01 +0000] "GET /c4_flatten HTTP/1.1" 200 614 "-" "Prometheus/2.54.1"
```
